import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navLinkClassName =
    "rounded-md bg-black px-3 py-2 text-sm font-medium text-white transition-colors hover:bg-black/80 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-black/40 focus-visible:ring-offset-2 dark:bg-white dark:text-black dark:hover:bg-white/80 dark:focus-visible:ring-white/40 dark:focus-visible:ring-offset-black";

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="border-b border-black/10 dark:border-white/10">
          <div className="mx-auto flex max-w-5xl flex-col items-center gap-3 px-4 py-4 sm:flex-row sm:justify-between">
            <Link
              href="/"
              id="brand"
              className="rounded-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-black/40 focus-visible:ring-offset-2 dark:focus-visible:ring-white/40 dark:focus-visible:ring-offset-black"
            >
              <img
                src="/manu-astro.png"
                alt="Manu Astro"
                className="h-10 w-10"
              />
            </Link>
            <nav className="flex flex-wrap items-center justify-center gap-2 sm:justify-end">
              <Link
                href="/"
                className={navLinkClassName}
              >
                Home
              </Link>
              <Link
                href="/about"
                className={navLinkClassName}
              >
                About
              </Link>
              <Link
                href="/server-time"
                className={navLinkClassName}
              >
                Server Time
              </Link>
            </nav>
          </div>
        </header>
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
